export const state = {
  data: {},
  theme: {},
};
state.theme = localStorage.getItem("theme") || 'black';


const data = [
  {
    id: 1,
    family: 'self-tapping',
    type: 'to_plasterboard',
    label: 'До гіпсокартону',
    name: 'Саморіз до гіпсокартону по металу',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 2,
    family: 'self-tapping',
    type: 'to_plasterboard',
    label: 'До гіпсокартону',
    name: 'Саморіз до гіпсокартону по дереву',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 3,
    family: 'self-tapping',
    type: 'to_plasterboard_tex',
    label: 'До гіпсокартону (TEX)',
    name: 'Саморіз до гіпсокартону (TEX) з буром',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 4,
    family: 'self-tapping',
    type: 'to_plasterboard_tex',
    label: 'До гіпсокартону (TEX)',
    name: 'Саморіз до гіпсокартону (TEX) без бура',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 5,
    family: 'self-tapping',
    type: 'roofing',
    label: 'Покрівельний',
    name: 'Саморіз покрівельний по металу з EPDM',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 6,
    family: 'self-tapping',
    type: 'roofing',
    label: 'Покрівельний',
    name: 'Саморіз покрівельний по дереву з EPDM',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 7,
    family: 'self-tapping',
    type: 'roofing',
    label: 'Покрівельний',
    name: 'Саморіз покрівельний без EPDM',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 8,
    family: 'self-tapping',
    type: 'with_press_washer',
    label: 'З пресшайбою',
    name: 'Саморіз з пресшайбою з буром',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 9,
    family: 'self-tapping',
    type: 'with_press_washer',
    label: 'З пресшайбою',
    name: 'Саморіз з пресшайбою без бура',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 10,
    family: 'self-tapping',
    type: 'wood',
    label: 'По дереву',
    name: 'Саморіз по дереву для лаг і рейок',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 11,
    family: 'self-tapping',
    type: 'wood',
    label: 'По дереву',
    name: 'Саморіз по дереву універсальний гартований',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 12,
    family: 'self-tapping',
    type: 'wood_construction',
    label: 'По дереву (Конструкційні)',
    name: 'Шуруп теслярський з пресшайбою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 13,
    family: 'self-tapping',
    type: 'wood_construction',
    label: 'По дереву (Конструкційні)',
    name: 'Шуруп теслярський з потайною голівкою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 14,
    family: 'self-tapping',
    type: 'wood_hook',
    label: 'По дереву (Шуруп-гак)',
    name: 'Шуруп-гак прямий',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 15,
    family: 'self-tapping',
    type: 'wood_hook',
    label: 'По дереву (Шуруп-гак)',
    name: 'Шуруп-гак півкруглий',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 16,
    family: 'self-tapping',
    type: 'wood_hook',
    label: 'По дереву (Шуруп-гак)',
    name: 'Шуруп-гак О-подібний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 17,
    family: 'self-tapping',
    type: 'window',
    label: 'Віконні',
    name: 'Турбошуруп',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 18,
    family: 'self-tapping',
    type: 'window',
    label: 'Віконні',
    name: 'Саморіз для ПВХ з потайною голівкою',
    like: 'no',
    bookmark: 'no',
  },

  {
    id: 19,
    family: 'metrics',
    type: 'nut',
    label: 'Гайка',
    name: 'Гайка шестигранна',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 20,
    family: 'metrics',
    type: 'nut',
    label: 'Гайка',
    name: 'Гайка самостопорна',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 21,
    family: 'metrics',
    type: 'nut',
    label: 'Гайка',
    name: 'Гайка ковпакова',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 22,
    family: 'metrics',
    type: 'nut',
    label: 'Гайка',
    name: 'Гайка з флянцем',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 23,
    family: 'metrics',
    type: 'nut',
    label: 'Гайка',
    name: 'Гайка подовжена',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 24,
    family: 'metrics',
    type: 'nut',
    label: 'Гайка',
    name: 'Гайка зубчаста',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 25,
    family: 'metrics',
    type: 'nut',
    label: 'Гайка',
    name: 'Гайка метелик',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 26,
    family: 'metrics',
    type: 'washer',
    label: 'Шайба',
    name: 'Шайба збільшена',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 27,
    family: 'metrics',
    type: 'washer',
    label: 'Шайба',
    name: "Шайба для дерев'яних конструкцій",
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 28,
    family: 'metrics',
    type: 'washer',
    label: 'Шайба',
    name: 'Шайба вузька',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 29,
    family: 'metrics',
    type: 'washer',
    label: 'Шайба',
    name: 'Шайба пружинна (Гровер)',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 30,
    family: 'metrics',
    type: 'bolt',
    label: 'Болт',
    name: 'Болт з шестигранною голівкою',
    like: 'no',
    bookmark: 'no',
  },

  {
    id: 31,
    family: 'metrics',
    type: 'bolt',
    label: 'Болт',
    name: 'Болт замковий гриб',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 32,
    family: 'metrics',
    type: 'screw',
    label: 'Гвинт',
    name: 'Гвинт з потайною голівкою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 33,
    family: 'metrics',
    type: 'screw',
    label: 'Гвинт',
    name: 'Гвинт з пресшайбою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 34,
    family: 'metrics',
    type: 'screw',
    label: 'Гвинт',
    name: 'Гвинт внутрішний шестигранник',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 35,
    family: 'metrics',
    type: 'stud',
    label: 'Шпилька',
    name: 'Шпилька двогвинтова',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 36,
    family: 'metrics',
    type: 'stud',
    label: 'Шпилька',
    name: 'Шпилька метрична',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 37,
    family: 'anchors',
    type: 'anchor',
    label: 'Анкер',
    name: 'Анкер однорозпірний з гайкою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 38,
    family: 'anchors',
    type: 'anchor',
    label: 'Анкер',
    name: 'Анкер-клин BIERBACH',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 39,
    family: 'anchors',
    type: 'anchor',
    label: 'Анкер',
    name: 'Анкер рамний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 40,
    family: 'anchors',
    type: 'bushing',
    label: 'Втулка',
    name: 'Втулка із сталі',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 41,
    family: 'anchors',
    type: 'bushing',
    label: 'Втулка',
    name: 'Втулка із латуні',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 42,
    family: 'anchors',
    type: 'bushing',
    label: 'Втулка',
    name: 'Втулка для хімічного анкера',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 43,
    family: 'anchors',
    type: 'umbrella',
    label: 'Парасолька',
    name: 'Дюбель до газобетону',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 44,
    family: 'anchors',
    type: 'umbrella',
    label: 'Парасолька',
    name: 'Розкладний пружинний анкер з гаком',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 45,
    family: 'anchors',
    type: 'umbrella',
    label: 'Парасолька',
    name: 'Розкладний пружинний анкер з кільцем',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 46,
    family: 'anchors',
    type: 'umbrella',
    label: 'Парасолька',
    name: 'Розкладний пружинний анкер з гайкою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 47,
    family: 'dowels',
    type: 'driving',
    label: 'Забивні',
    name: 'Розпірний дюбель з комірцем і вусами',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 48,
    family: 'dowels',
    type: 'driving',
    label: 'Забивні',
    name: 'Розпірний дюбель без комірця з вусами',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 49,
    family: 'dowels',
    type: 'driving',
    label: 'Забивні',
    name: 'Дюбель з цвях-шурупом з комірцем',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 50,
    family: 'dowels',
    type: 'driving',
    label: 'Забивні',
    name: 'Дюбель з цвях-шурупом без комірця',
    like: 'no',
    bookmark: 'no',
  },

  {
    id: 51,
    family: 'dowels',
    type: 'hollow',
    label: 'Пусті',
    name: 'Дюбель пустий універсальний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 52,
    family: 'dowels',
    type: 'hollow',
    label: 'Пусті',
    name: 'Дюбель пустий рамний (подовжений)',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 53,
    family: 'dowels',
    type: 'hollow_materials',
    label: 'Для пустотілих матеріалів',
    name: 'Дюбель DRIVA',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 54,
    family: 'dowels',
    type: 'hollow_materials',
    label: 'Для пустотілих матеріалів',
    name: 'Дюбель DRIVA металевий',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 55,
    family: 'dowels',
    type: 'hollow_materials',
    label: 'Для пустотілих матеріалів',
    name: 'Дюбель метелик з шурупом',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 56,
    family: 'dowels',
    type: 'kits',
    label: 'Комплекти',
    name: 'Дюбель + саморіз під PZ',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 57,
    family: 'dowels',
    type: 'kits',
    label: 'Комплекти',
    name: 'Дюбель + саморіз із шестигранною голівкою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 58,
    family: 'dowels',
    type: 'kits',
    label: 'Комплекти',
    name: 'Дюбель + гак прямий',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 59,
    family: 'dowels',
    type: 'kits',
    label: 'Комплекти',
    name: 'Дюбель + гак півкруглий',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 60,
    family: 'dowels',
    type: 'kits',
    label: 'Комплекти',
    name: 'Дюбель + гак О-подібний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 61,
    family: 'dowels',
    type: 'kits',
    label: 'Комплекти',
    name: 'Дюбель HOX',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 62,
    family: 'dowels',
    type: 'thermal_insulation',
    label: 'Термоізоляція',
    name: 'Дюбель до пінопласту з пластиковим цвяхом',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 63,
    family: 'dowels',
    type: 'thermal_insulation',
    label: 'Термоізоляція',
    name: 'Дюбель до мінвати з посиленою термоголівкою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 64,
    family: 'dowels',
    type: 'thermal_insulation',
    label: 'Термоізоляція',
    name: 'Дюбель до мінвати з термоголівкою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 65,
    family: 'dowels',
    type: 'accessories',
    label: 'Комплектуючі',
    name: 'Фреза',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 66,
    family: 'dowels',
    type: 'accessories',
    label: 'Комплектуючі',
    name: 'Рондоль',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 67,
    family: 'dowels',
    type: 'accessories',
    label: 'Комплектуючі',
    name: 'Заглушка',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 68,
    family: 'rigging',
    type: 'chains',
    label: 'Ланцюги',
    name: 'Ланцюг коротка ланка',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 69,
    family: 'rigging',
    type: 'chains',
    label: 'Ланцюги',
    name: 'Ланцюг довга ланка',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 70,
    family: 'rigging',
    type: 'wire_rope',
    label: 'Трос',
    name: 'Трос оцинкований DIN 3053',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 71,
    family: 'rigging',
    type: 'wire_rope',
    label: 'Трос',
    name: 'Трос оцинкований DIN 3060',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 72,
    family: 'rigging',
    type: 'wire_rope',
    label: 'Трос',
    name: 'Трос оцинкований в ПВХ обплетенні',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 73,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Карабін пожежний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 74,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Карабін пожежний з фіксатором',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 75,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Карабін-гвинт',
    like: 'no',
    bookmark: 'no',
  },

  {
    id: 76,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Карабін U-подібний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 77,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Карабін з вертлюгом',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 78,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Вертлюг нікельований',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 79,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Рим-гайка',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 80,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Рим-болт',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 81,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Шпилька з кільцем',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 82,
    family: 'rigging',
    type: 'chain_accessories',
    label: 'Комплектуючі для ланцюга',
    name: 'Гак S-подібний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 83,
    family: 'rigging',
    type: 'wire_rope_accessories_clamp',
    label: 'Зажими для троса',
    name: 'Зажим для троса П-подібний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 84,
    family: 'rigging',
    type: 'wire_rope_accessories_clamp',
    label: 'Зажими для троса',
    name: 'Зажим для троса SIMPLEX',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 85,
    family: 'rigging',
    type: 'wire_rope_accessories_clamp',
    label: 'Зажими для троса',
    name: 'Зажим для троса DUPLEX',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 86,
    family: 'rigging',
    type: 'wire_rope_accessories',
    label: 'Комплектуючі для кріплення троса',
    name: 'Коуш',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 87,
    family: 'rigging',
    type: 'wire_rope_accessories',
    label: 'Комплектуючі для кріплення троса',
    name: 'Гак для строп',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 88,
    family: 'rigging',
    type: 'wire_rope_accessories',
    label: 'Комплектуючі для кріплення троса',
    name: 'Блок одинарний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 89,
    family: 'rigging',
    type: 'wire_rope_accessories',
    label: 'Комплектуючі для кріплення троса',
    name: 'Блок подвійний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 90,
    family: 'rigging',
    type: 'wire_rope_accessories',
    label: 'Комплектуючі для кріплення троса',
    name: 'Гак-гак',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 91,
    family: 'rigging',
    type: 'wire_rope_accessories',
    label: 'Комплектуючі для кріплення троса',
    name: 'Гак-кільце',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 92,
    family: 'rigging',
    type: 'wire_rope_accessories',
    label: 'Комплектуючі для кріплення троса',
    name: 'Кільце-кільце',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 93,
    family: 'carpentry',
    type: 'corner_brackets',
    label: 'Кутник панельний',
    name: 'Кутник посилений ребром жорсткості',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 94,
    family: 'carpentry',
    type: 'corner_brackets',
    label: 'Кутник панельний',
    name: 'Кутник без ребра жорсткості',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 95,
    family: 'carpentry',
    type: 'corner_brackets',
    label: 'Кутник панельний',
    name: 'Кутник без покриття',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 96,
    family: 'carpentry',
    type: 'beam_hangers',
    label: 'Підвіс балки WB',
    name: 'Підвіс балки відкритий',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 97,
    family: 'carpentry',
    type: 'beam_hangers',
    label: 'Підвіс балки WB',
    name: 'Підвіс балки закритий',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 98,
    family: 'carpentry',
    type: 'beam_supports',
    label: 'Опора балки, пластина',
    name: 'Опора балки нерегульована',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 99,
    family: 'carpentry',
    type: 'beam_supports',
    label: 'Опора балки, пластина',
    name: 'Опора балки регульована',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 100,
    family: 'carpentry',
    type: 'beam_supports',
    label: 'Опора балки, пластина',
    name: 'Пластина перфорована',
    like: 'no',
    bookmark: 'no',
  },

  {
    id: 101,
    family: 'carpentry',
    type: 'furniture_fittings',
    label: 'Кріплення меблеве',
    name: 'Підвіс меблевий',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 102,
    family: 'carpentry',
    type: 'furniture_fittings',
    label: 'Кріплення меблеве',
    name: 'Підвіс для дзеркала',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 103,
    family: 'instruments',
    type: 'drills',
    label: 'Свердло',
    name: 'Свердло по бетону SDS-PLUS',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 104,
    family: 'instruments',
    type: 'drills',
    label: 'Свердло',
    name: 'Свердло по бетону SDS-MAX',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 105,
    family: 'instruments',
    type: 'drills',
    label: 'Свердло',
    name: 'Свердло по металу HSS',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 106,
    family: 'instruments',
    type: 'drills',
    label: 'Свердло',
    name: 'Свердло по дереву спіральне',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 107,
    family: 'instruments',
    type: 'drills',
    label: 'Свердло',
    name: 'Свердло по дереву перове',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 108,
    family: 'instruments',
    type: 'drills',
    label: 'Свердло',
    name: 'Свердло по склу і кераміці',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 109,
    family: 'instruments',
    type: 'drills',
    label: 'Свердло',
    name: 'Свердло по склу і кераміці з шестигранником',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 110,
    family: 'instruments',
    type: 'bits_and_accessories',
    label: 'Біти й насадки',
    name: 'Біта PHILLIPS (PH)',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 111,
    family: 'instruments',
    type: 'bits_and_accessories',
    label: 'Біти й насадки',
    name: 'Біта POZIDRIVE (PZ)',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 112,
    family: 'instruments',
    type: 'bits_and_accessories',
    label: 'Біти й насадки',
    name: 'Біта TORX',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 113,
    family: 'instruments',
    type: 'bits_and_accessories',
    label: 'Біти й насадки',
    name: 'Біта з обмежувачем',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 114,
    family: 'instruments',
    type: 'bits_and_accessories',
    label: 'Біти й насадки',
    name: 'Біта шестигранна',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 115,
    family: 'instruments',
    type: 'bits_and_accessories',
    label: 'Біти й насадки',
    name: 'Подовжувач магнітний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 116,
    family: 'instruments',
    type: 'bits_and_accessories',
    label: 'Біти й насадки',
    name: 'Подовжувач магнітний для шестигранних голівок',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 117,
    family: 'instruments',
    type: 'bits_and_accessories',
    label: 'Біти й насадки',
    name: 'Подовжувач магнітний з фіксатором',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 118,
    family: 'instruments',
    type: 'saw_blades',
    label: 'Пилки / Полотно по металу',
    name: 'Полотно до електролобзика PROSERIES',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 119,
    family: 'instruments',
    type: 'saw_blades',
    label: 'Пилки / Полотно по металу',
    name: 'Полотно до електролобзика',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 120,
    family: 'instruments',
    type: 'abrasives',
    label: 'Абразивні матеріали',
    name: 'Круги відрізні',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 121,
    family: 'instruments',
    type: 'abrasives',
    label: 'Абразивні матеріали',
    name: 'Круги шліфувальні',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 122,
    family: 'instruments',
    type: 'abrasives',
    label: 'Абразивні матеріали',
    name: 'Круги пелюсткові',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 123,
    family: 'instruments',
    type: 'abrasives',
    label: 'Абразивні матеріали',
    name: 'Круги шліфувальні на ліпучці',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 124,
    family: 'instruments',
    type: 'abrasives',
    label: 'Абразивні матеріали',
    name: 'Сітка шліфувальна',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 125,
    family: 'instruments',
    type: 'measuring',
    label: 'Вимірювальний інструмент',
    name: 'Рулетка магнітна з 2 автостопорами',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 126,
    family: 'instruments',
    type: 'measuring',
    label: 'Вимірювальний інструмент',
    name: 'Рулетка магнітна з автостопором та 2 фіксаторами',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 127,
    family: 'instruments',
    type: 'measuring',
    label: 'Вимірювальний інструмент',
    name: 'Рулетка магнітна з 3 автостопорами',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 128,
    family: 'instruments',
    type: 'fastening_instruments',
    label: 'Кріпильний інструмент',
    name: 'Скоби',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 129,
    family: 'instruments',
    type: 'fastening_instruments',
    label: 'Кріпильний інструмент',
    name: 'Заклепки',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 130,
    family: 'instruments',
    type: 'riveters',
    label: 'Пістолет',
    name: 'Пістолет заклепочний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 131,
    family: 'instruments',
    type: 'riveters',
    label: 'Пістолет',
    name: 'Пістолет заклепочний хромований',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 132,
    family: 'others',
    type: 'miscellaneous',
    label: 'Різне',
    name: 'Дюбель ялинка',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 133,
    family: 'others',
    type: 'miscellaneous',
    label: 'Різне',
    name: 'Дюбель прямий',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 134,
    family: 'others',
    type: 'miscellaneous',
    label: 'Різне',
    name: 'Ізоляційна стрічка ПВХ',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 135,
    family: 'others',
    type: 'miscellaneous',
    label: 'Різне',
    name: 'Кабельні стяжки',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 136,
    family: 'others',
    type: 'miscellaneous',
    label: 'Різне',
    name: 'Щітка пензель',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 137,
    family: 'others',
    type: 'miscellaneous',
    label: 'Різне',
    name: 'Хомут сантехнічний',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 138,
    family: 'others',
    type: 'miscellaneous',
    label: 'Різне',
    name: 'Хомут сантехнічний у комплекті з шпилькою',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 139,
    family: 'others',
    type: 'miscellaneous',
    label: 'Різне',
    name: 'Хомут сантехнічний фарбований',
    like: 'no',
    bookmark: 'no',
  },
  {
    id: 140,
    family: 'others',
    type: 'miscellaneous',
    label: 'Різне',
    name: "Хомут черв'ячний",
    like: 'no',
    bookmark: 'no',
  },
];

export async function fetchData() {
  try {
    if (localStorage.getItem('data')) {
      state.data = JSON.parse(localStorage.getItem('data'));
    } else {
      state.data = data
    }
  } catch (error) {
    console.error(`Server didn't respond! ${error}`);
  }
}

export function setState(state) {
  localStorage.setItem('state', state);
}