import express, { json } from "express";
import cors from "cors";

const app = express();
const port = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

const data = [
  {
    id: 1,
    family: "Саморіз",
    type: "До гіпсокартону",
    name: "Саморіз до гіпсокартону по металу",
    like: "no",
    bookmark: "no",
  },
  {
    id: 2,
    family: "Саморіз",
    type: "До гіпсокартону",
    name: "Саморіз до гіпсокартону по дереву",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 3,
    family: "Саморіз",
    type: "До гіпсокартону (TEX)",
    name: "Саморіз до гіпсокартону (TEX) з буром",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 4,
    family: "Саморіз",
    type: "До гіпсокартону (TEX)",
    name: "Саморіз до гіпсокартону (TEX) без бура",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 5,
    family: "Саморіз",
    type: "Покрівельний",
    name: "Саморіз покрівельний по металу з EPDM",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 6,
    family: "Саморіз",
    type: "Покрівельний",
    name: "Саморіз покрівельний по дереву з EPDM ",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 7,
    family: "Саморіз",
    type: "Покрівельний",
    name: "Саморіз покрівельний без EPDM",
    like: "no",
    bookmark: "no",
  },
  {
    id: 8,
    family: "Саморіз",
    type: "З пресшайбою",
    name: "Саморіз з пресшайбою з буром",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 9,
    family: "Саморіз",
    type: "З пресшайбою",
    name: "Саморіз з пресшайбою без бура",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 10,
    family: "Саморіз",
    type: "По дереву",
    name: "Саморіз по дереву для лаг і рейок",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 11,
    family: "Саморіз",
    type: "По дереву",
    name: "Саморіз по дереву універсальний гартований",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 12,
    family: "Саморіз",
    type: "По дереву (Конструкційні)",
    name: "Шуруп теслярський з пресшайбою",
    like: "no",
    bookmark: "no",
  },
  {
    id: 13,
    family: "Саморіз",
    type: "По дереву (Конструкційні)",
    name: "Шуруп теслярський з потайною голівкою",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 14,
    family: "Саморіз",
    type: "По дереву (Шуруп-гак)",
    name: "Шуруп-гак прямий",
    like: "no",
    bookmark: "no",
  },
  {
    id: 15,
    family: "Саморіз",
    type: "По дереву (Шуруп-гак)",
    name: "Шуруп-гак півкруглий",
    like: "no",
    bookmark: "no",
  },
  {
    id: 16,
    family: "Саморіз",
    type: "По дереву (Шуруп-гак)",
    name: "Шуруп-гак О-подібний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 17,
    family: "Саморіз",
    type: "Віконні",
    name: "Турбошуруп",
    like: "no",
    bookmark: "no",
  },
  {
    id: 18,
    family: "Саморіз",
    type: "Віконні",
    name: "Саморіз для ПВХ з потайною голівкою",
    like: "yes",
    bookmark: "no",
  },

  {
    id: 19,
    family: "Метричні вироби",
    type: "Гайка",
    name: "Гайка шестигранна",
    like: "no",
    bookmark: "no",
  },
  {
    id: 20,
    family: "Метричні вироби",
    type: "Гайка",
    name: "Гайка самостопорна",
    like: "no",
    bookmark: "no",
  },
  {
    id: 21,
    family: "Метричні вироби",
    type: "Гайка",
    name: "Гайка ковпакова",
    like: "no",
    bookmark: "no",
  },
  {
    id: 22,
    family: "Метричні вироби",
    type: "Гайка",
    name: "Гайка з флянцем",
    like: "no",
    bookmark: "no",
  },
  {
    id: 23,
    family: "Метричні вироби",
    type: "Гайка",
    name: "Гайка подовжена",
    like: "no",
    bookmark: "no",
  },
  {
    id: 24,
    family: "Метричні вироби",
    type: "Гайка",
    name: "Гайка зубчаста",
    like: "no",
    bookmark: "no",
  },
  {
    id: 25,
    family: "Метричні вироби",
    type: "Гайка",
    name: "Гайка метелик",
    like: "no",
    bookmark: "no",
  },
  {
    id: 26,
    family: "Метричні вироби",
    type: "Шайба",
    name: "Шайба збільшена",
    like: "no",
    bookmark: "no",
  },
  {
    id: 27,
    family: "Метричні вироби",
    type: "Шайба",
    name: "Шайба для дерев'яних конструкцій",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 28,
    family: "Метричні вироби",
    type: "Шайба",
    name: "Шайба вузька",
    like: "no",
    bookmark: "no",
  },
  {
    id: 29,
    family: "Метричні вироби",
    type: "Шайба",
    name: "Шайба пружинна (Гровер)",
    like: "no",
    bookmark: "no",
  },
  {
    id: 30,
    family: "Метричні вироби",
    type: "Болт",
    name: "Болт з шестигранною голівкою",
    like: "no",
    bookmark: "no",
  },
  {
    id: 31,
    family: "Метричні вироби",
    type: "Болт",
    name: "Болт замковий гриб",
    like: "no",
    bookmark: "no",
  },
  {
    id: 32,
    family: "Метричні вироби",
    type: "Гвинт",
    name: "Гвинт з потайною голівкою",
    like: "no",
    bookmark: "no",
  },
  {
    id: 33,
    family: "Метричні вироби",
    type: "Гвинт",
    name: "Гвинт з пресшайбою",
    like: "no",
    bookmark: "no",
  },
  {
    id: 34,
    family: "Метричні вироби",
    type: "Гвинт",
    name: "Гвинт внутрішний шестигранник",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 35,
    family: "Метричні вироби",
    type: "Шпилька",
    name: "Шпилька двогвинтова",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 36,
    family: "Метричні вироби",
    type: "Шпилька",
    name: "Шпилька метрична",
    like: "yes",
    bookmark: "no",
  },

  {
    id: 37,
    family: "Анкерне кріплення",
    type: "Анкер",
    name: "Анкер однорозпірний з гайкою",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 38,
    family: "Анкерне кріплення",
    type: "Анкер",
    name: "Анкер-клин BIERBACH",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 39,
    family: "Анкерне кріплення",
    type: "Анкер",
    name: "Анкер рамний",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 40,
    family: "Анкерне кріплення",
    type: "Втулка ",
    name: "Втулка із сталі",
    like: "no",
    bookmark: "no",
  },
  {
    id: 41,
    family: "Анкерне кріплення",
    type: "Втулка ",
    name: "Втулка із латуні",
    like: "no",
    bookmark: "no",
  },
  {
    id: 42,
    family: "Анкерне кріплення",
    type: "Втулка ",
    name: "Втулка для хімічного анкера",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 43,
    family: "Анкерне кріплення",
    type: "Парасолька",
    name: "Дюбель до газобетону",
    like: "no",
    bookmark: "no",
  },
  {
    id: 44,
    family: "Анкерне кріплення",
    type: "Парасолька",
    name: "Розкладний пружинний анкер з гаком",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 45,
    family: "Анкерне кріплення",
    type: "Парасолька",
    name: "Розкладний пружинний анкер з кільцем",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 46,
    family: "Анкерне кріплення",
    type: "Парасолька",
    name: "Розкладний пружинний анкер з гайкою",
    like: "yes",
    bookmark: "no",
  },

  {
    id: 47,
    family: "Дюбелі",
    type: "Забивні",
    name: "Розпірний дюбель з комірцем і вусами",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 48,
    family: "Дюбелі",
    type: "Забивні",
    name: "Розпірний дюбель без комірця з вусами",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 49,
    family: "Дюбелі",
    type: "Забивні",
    name: "Дюбель з цвях-шурупом з комірцем",
    like: "no",
    bookmark: "no",
  },
  {
    id: 50,
    family: "Дюбелі",
    type: "Забивні",
    name: "Дюбель з цвях-шурупом без комірця",
    like: "no",
    bookmark: "no",
  },
  {
    id: 51,
    family: "Дюбелі",
    type: "Пусті",
    name: "Дюбель пустий універсальний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 52,
    family: "Дюбелі",
    type: "Пусті",
    name: "Дюбель пустий рамний (подовжений)",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 53,
    family: "Дюбелі",
    type: "Для пустотілих матеріалів",
    name: "Дюбель DRIVA",
    like: "no",
    bookmark: "no",
  },
  {
    id: 54,
    family: "Дюбелі",
    type: "Для пустотілих матеріалів",
    name: "Дюбель DRIVA металевий",
    like: "no",
    bookmark: "no",
  },
  {
    id: 55,
    family: "Дюбелі",
    type: "Для пустотілих матеріалів",
    name: "Дюбель метелик з шурупом",
    like: "no",
    bookmark: "no",
  },
  {
    id: 56,
    family: "Дюбелі",
    type: "Комплекти",
    name: "Дюбель + саморіз під PZ",
    like: "no",
    bookmark: "no",
  },
  {
    id: 57,
    family: "Дюбелі",
    type: "Комплекти",
    name: "Дюбель + саморіз із шестигранною голівкою",
    like: "no",
    bookmark: "no",
  },
  {
    id: 58,
    family: "Дюбелі",
    type: "Комплекти",
    name: "Дюбель + гак прямий",
    like: "no",
    bookmark: "no",
  },
  {
    id: 59,
    family: "Дюбелі",
    type: "Комплекти",
    name: "Дюбель + гак півкруглий",
    like: "no",
    bookmark: "no",
  },
  {
    id: 60,
    family: "Дюбелі",
    type: "Комплекти",
    name: "Дюбель + гак О-подібний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 61,
    family: "Дюбелі",
    type: "Комплекти",
    name: "Дюбель HOX",
    like: "no",
    bookmark: "no",
  },
  {
    id: 62,
    family: "Дюбелі",
    type: "Термоізоляція",
    name: "Дюбель до пінопласту з пластиковим цвяхом",
    like: "yes",
    bookmark: "yes",
  },
  {
    id: 63,
    family: "Дюбелі",
    type: "Термоізоляція",
    name: "Дюбель до мінвати з посиленою термоголівкою",
    like: "yes",
    bookmark: "yes",
  },
  {
    id: 64,
    family: "Дюбелі",
    type: "Термоізоляція",
    name: "Дюбель до мінвати з термоголівкою",
    like: "no",
    bookmark: "no",
  },
  {
    id: 65,
    family: "Дюбелі",
    type: "Комплектуючі",
    name: "Фреза",
    like: "no",
    bookmark: "no",
  },
  {
    id: 66,
    family: "Дюбелі",
    type: "Комплектуючі",
    name: "Рондоль",
    like: "no",
    bookmark: "no",
  },
  {
    id: 67,
    family: "Дюбелі",
    type: "Комплектуючі",
    name: "Заглушка",
    like: "no",
    bookmark: "no",
  },

  {
    id: 68,
    family: "Такелаж",
    type: "Ланцюги",
    name: "Ланцюг коротка ланка",
    like: "no",
    bookmark: "no",
  },
  {
    id: 69,
    family: "Такелаж",
    type: "Ланцюги",
    name: "Ланцюг довга ланка",
    like: "no",
    bookmark: "no",
  },
  {
    id: 70,
    family: "Такелаж",
    type: "Трос",
    name: "Трос оцинкований DIN 3053",
    like: "no",
    bookmark: "no",
  },
  {
    id: 71,
    family: "Такелаж",
    type: "Трос",
    name: "Трос оцинкований DIN 3060",
    like: "no",
    bookmark: "no",
  },
  {
    id: 72,
    family: "Такелаж",
    type: "Трос",
    name: "Трос оцинкований в ПВХ обплетенні",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 73,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Карабін пожежний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 74,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Карабін пожежний з фіксатором",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 75,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Карабін-гвинт",
    like: "no",
    bookmark: "no",
  },
  {
    id: 76,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Карабін U-подібний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 77,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Карабін з вертлюгом",
    like: "no",
    bookmark: "no",
  },
  {
    id: 78,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Вертлюг нікельований",
    like: "no",
    bookmark: "no",
  },
  {
    id: 79,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Рим-гайка",
    like: "no",
    bookmark: "no",
  },
  {
    id: 80,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Рим-болт",
    like: "no",
    bookmark: "no",
  },
  {
    id: 81,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Шпилька з кільцем",
    like: "no",
    bookmark: "no",
  },
  {
    id: 82,
    family: "Такелаж",
    type: "Комплектуючі для ланцюга",
    name: "Гак S-подібний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 83,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса (Зажими для троса)",
    name: "Зажим для троса П-подібний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 84,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса (Зажими для троса)",
    name: "Зажим для троса SIMPLEX",
    like: "no",
    bookmark: "no",
  },
  {
    id: 85,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса (Зажими для троса)",
    name: "Зажим для троса DUPLEX",
    like: "no",
    bookmark: "no",
  },
  {
    id: 86,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса",
    name: "Коуш",
    like: "no",
    bookmark: "no",
  },
  {
    id: 87,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса",
    name: "Гак для строп",
    like: "no",
    bookmark: "no",
  },
  {
    id: 88,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса",
    name: "Блок одинарний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 89,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса",
    name: "Блок подвійний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 90,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса",
    name: "Гак-гак",
    like: "no",
    bookmark: "no",
  },
  {
    id: 91,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса",
    name: "Гак-кільце",
    like: "no",
    bookmark: "no",
  },
  {
    id: 92,
    family: "Такелаж",
    type: "Комплектуючі для кріплення троса",
    name: "Кільце-кільце",
    like: "no",
    bookmark: "no",
  },

  {
    id: 93,
    family: "Столярне кріплення",
    type: "Кутник панельний",
    name: "Кутник посилений ребром жорсткості",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 94,
    family: "Столярне кріплення",
    type: "Кутник панельний",
    name: "Кутник без ребра жорсткосі",
    like: "no",
    bookmark: "no",
  },
  {
    id: 95,
    family: "Столярне кріплення",
    type: "Кутник панельний",
    name: "Кутник без покриття",
    like: "no",
    bookmark: "no",
  },
  {
    id: 96,
    family: "Столярне кріплення",
    type: "Підвіс балки WB",
    name: "Підвіс балки відкритий",
    like: "no",
    bookmark: "no",
  },
  {
    id: 97,
    family: "Столярне кріплення",
    type: "Підвіс балки WB",
    name: "Підвіс балки закритий",
    like: "no",
    bookmark: "no",
  },
  {
    id: 98,
    family: "Столярне кріплення",
    type: "Опора балки, пластина",
    name: "Опора балки нерегульована",
    like: "no",
    bookmark: "no",
  },
  {
    id: 99,
    family: "Столярне кріплення",
    type: "Опора балки, пластина",
    name: "Опора балки регульована",
    like: "no",
    bookmark: "no",
  },
  {
    id: 100,
    family: "Столярне кріплення",
    type: "Опора балки, пластина",
    name: "Пластина перфорована",
    like: "no",
    bookmark: "no",
  },
  {
    id: 101,
    family: "Столярне кріплення",
    type: "Кріплення меблеве",
    name: "Підвіс меблевий",
    like: "no",
    bookmark: "no",
  },
  {
    id: 102,
    family: "Столярне кріплення",
    type: "Кріплення меблеве",
    name: "Підвіс для дзеркала",
    like: "no",
    bookmark: "no",
  },

  {
    id: 103,
    family: "Інструменти",
    type: "Свердло",
    name: "Свердло по бетону SDS-PLUS",
    like: "no",
    bookmark: "no",
  },
  {
    id: 104,
    family: "Інструменти",
    type: "Свердло",
    name: "Свердло по бетону SDS-MAX",
    like: "no",
    bookmark: "no",
  },
  {
    id: 105,
    family: "Інструменти",
    type: "Свердло",
    name: "Свердло по металу HSS",
    like: "no",
    bookmark: "no",
  },
  {
    id: 106,
    family: "Інструменти",
    type: "Свердло",
    name: "Свердло по дереву спіральне",
    like: "no",
    bookmark: "no",
  },
  {
    id: 107,
    family: "Інструменти",
    type: "Свердло",
    name: "Свердло по дереву перове",
    like: "no",
    bookmark: "no",
  },
  {
    id: 108,
    family: "Інструменти",
    type: "Свердло",
    name: "Свердло по склу і кераміці",
    like: "no",
    bookmark: "no",
  },
  {
    id: 109,
    family: "Інструменти",
    type: "Свердло",
    name: "Свердло по склу і кераміці з шестигранником",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 110,
    family: "Інструменти",
    type: "Біти й насадки",
    name: "Біта PHILLIPS (PH)",
    like: "no",
    bookmark: "no",
  },
  {
    id: 111,
    family: "Інструменти",
    type: "Біти й насадки",
    name: "Біта POZIDRIVE (PZ)",
    like: "no",
    bookmark: "no",
  },
  {
    id: 112,
    family: "Інструменти",
    type: "Біти й насадки",
    name: "Біта TORX",
    like: "no",
    bookmark: "no",
  },
  {
    id: 113,
    family: "Інструменти",
    type: "Біти й насадки",
    name: "Біта з обмежувачем",
    like: "no",
    bookmark: "no",
  },
  {
    id: 114,
    family: "Інструменти",
    type: "Біти й насадки",
    name: "Біта шестигранна",
    like: "no",
    bookmark: "no",
  },
  {
    id: 115,
    family: "Інструменти",
    type: "Біти й насадки",
    name: "Подовжувач магнітний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 116,
    family: "Інструменти",
    type: "Біти й насадки",
    name: "Подовжувач магнітний для шестигранних голівок",
    like: "no",
    bookmark: "no",
  },
  {
    id: 117,
    family: "Інструменти",
    type: "Біти й насадки",
    name: "Подовжувач магнітний з фіксатором",
    like: "no",
    bookmark: "no",
  },
  {
    id: 118,
    family: "Інструменти",
    type: "Пилки / Полотно по металу",
    name: "Полотна до електролобзика PROSERIES",
    like: "no",
    bookmark: "no",
  },
  {
    id: 119,
    family: "Інструменти",
    type: "Пилки / Полотно по металу",
    name: "Полотна до електролобзика",
    like: "no",
    bookmark: "no",
  },
  {
    id: 120,
    family: "Інструменти",
    type: "Абразивні матеріали",
    name: "Круги відрізні",
    like: "no",
    bookmark: "no",
  },
  {
    id: 121,
    family: "Інструменти",
    type: "Абразивні матеріали",
    name: "Круги шліфувальні",
    like: "no",
    bookmark: "no",
  },
  {
    id: 122,
    family: "Інструменти",
    type: "Абразивні матеріали",
    name: "Круги пелюсткові",
    like: "no",
    bookmark: "no",
  },
  {
    id: 123,
    family: "Інструменти",
    type: "Абразивні матеріали",
    name: "Круги шліфувальні на ліпучці",
    like: "no",
    bookmark: "no",
  },
  {
    id: 124,
    family: "Інструменти",
    type: "Абразивні матеріали",
    name: "Сітка шліфувальна",
    like: "no",
    bookmark: "no",
  },
  {
    id: 125,
    family: "Інструменти",
    type: "Вимірювальний інструмент",
    name: "Рулетка магнітна з 2 автостопорами",
    like: "no",
    bookmark: "no",
  },
  {
    id: 126,
    family: "Інструменти",
    type: "Вимірювальний інструмент",
    name: "Рулетка магнітна з автостопором та 2 фіксаторами",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 127,
    family: "Інструменти",
    type: "Вимірювальний інструмент",
    name: "Рулетка магнітна з 3 автостопорами",
    like: "no",
    bookmark: "no",
  },
  {
    id: 128,
    family: "Інструменти",
    type: "Кріпильний інструмент",
    name: "Скоби",
    like: "no",
    bookmark: "no",
  },
  {
    id: 129,
    family: "Інструменти",
    type: "Кріпильний інструмент",
    name: "Заклепки",
    like: "no",
    bookmark: "no",
  },
  {
    id: 130,
    family: "Інструменти",
    type: "Пістолет",
    name: "Пістолет заклепочний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 131,
    family: "Інструменти",
    type: "Пістолет",
    name: "Пістолет заклепочний хромований",
    like: "no",
    bookmark: "no",
  },

  {
    id: 132,
    family: "Різне",
    type: "Різне",
    name: "Дюбель ялинка",
    like: "no",
    bookmark: "no",
  },
  {
    id: 133,
    family: "Різне",
    type: "Різне",
    name: "Дюбель прямий",
    like: "no",
    bookmark: "no",
  },
  {
    id: 134,
    family: "Різне",
    type: "Різне",
    name: "Ізоляційна стрічка ПВХ",
    like: "no",
    bookmark: "no",
  },
  {
    id: 135,
    family: "Різне",
    type: "Різне",
    name: "Кабельні стяжки",
    like: "no",
    bookmark: "no",
  },
  {
    id: 136,
    family: "Різне",
    type: "Різне",
    name: "Щітка пензель",
    like: "no",
    bookmark: "no",
  },
  {
    id: 137,
    family: "Різне",
    type: "Різне",
    name: "Хомут сантехнічний",
    like: "no",
    bookmark: "no",
  },
  {
    id: 138,
    family: "Різне",
    type: "Різне",
    name: "Хомут сантехнічний у комплекті з шпилькою",
    like: "yes",
    bookmark: "no",
  },
  {
    id: 139,
    family: "Різне",
    type: "Різне",
    name: "Хомут сантехнічний фарбований",
    like: "no",
    bookmark: "no",
  },
  {
    id: 140,
    family: "Різне",
    type: "Різне",
    name: "Хомут черв'ячний",
    like: "no",
    bookmark: "no",
  },
];

app.get("/data", (req, res) => {
  res.json(data);
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});
